version: '3.7'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: unless-stopped
    ports:
      - '3000:${FASTIFY_PORT:-3000}'
    init: true
    depends_on:
      - postgres
    networks:
      - fastify-net

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/db/postgres
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_DATABASE: ${DB_NAME:-birthday}
      POSTGRES_PASSWORD: ${DB_PASS:-V3ryS3cureP4ssw0rd}
    networks:
      - fastify-net

volumes:
  postgres_data:
    driver: local

networks:
  fastify-net: